### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError:

### ISSUE THREAD

**Issue by felinto-dev** [fjodor-rybakov/nestjs-dynamic-providers#5]
I was defining a constant in my app and this error was triggered.

![image](https://user-images.githubusercontent.com/32253743/142401271-a593e053-b27a-4cef-aef6-923329697405.png)

```sh
(node:13476) UnhandledPromiseRejectionWarning: TypeError: 
    at Object.hasOwnMetadata (/home/node/hotjoin-bot/node_modules/reflect-metadata/Reflect.js:312:23)
    at filterPredicate (/home/node/hotjoin-bot/src/telegram/menu/telegram-menu.module.ts:15:13)
    at Array.filter (<anonymous>)
    at /home/node/hotjoin-bot/node_modules/nestjs-dynamic-providers/dist/service/resolve-file.service.js:15:30
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13476) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13476) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I am using the last available version (v0.1.0)

```ts
@InjectDynamicProviders({
  pattern: 'dist/src/telegram/**/*.bot.js',
  filterPredicate: (type: Type) =>
    Reflect.hasOwnMetadata(UPDATE_METADATA, type),
})
@Module({
  imports: [
    CacheModule.register({
      ttl: 60 * 15, // 15 minutes
    }),
    ProductsModule,
    NotificationModule,
    AuthModule,
    ProducersModule,
    PlatformsModule,
    TgMenuModule,
  ],
  exports: [CacheModule],
})
export class TelegramMenuModule {}
```

**Comment by fjodor-rybakov** [comment]
Fixed in 0.1.1 version!

**Comment by felinto-dev** [comment]
I still get the same error. I updated for the last available version.

I don't mean to be rude but I think the ideal would be to keep the issue open until the creator can confirm the issue has been resolved or close it for inactivity.

**Comment by fjodor-rybakov** [comment]
> I still get the same error. I updated for the last available verson.

Sorry, forgot to tell. 
Replace:
```typescript
@InjectDynamicProviders({
  pattern: 'dist/src/telegram/**/*.bot.js',
  filterPredicate: (type: Type) =>
    Reflect.hasOwnMetadata(UPDATE_METADATA, type),
})
```
To:
```typescript
@InjectDynamicProviders({
  pattern: 'dist/src/telegram/**/*.bot.js',
  filterPredicate: (type: Type) =>
    IsObject(type) &&
    Reflect.hasOwnMetadata(UPDATE_METADATA, type),
})
```

> Import `IsObject` from nestjs-dynamic-providers

**Comment by felinto-dev** [comment]
I replicated the solution and was able to confirm that it works. You can close the issue now 👍
